spring:
  application:
    name: discoveryserver
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: prod
server:
  port: 9000